Tugas_2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_1.urls as app_1
import app_2.urls as app_2
import app_4.urls as app_4
import app_3.urls as app_3
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app-1/', include(app_1, namespace='app-1')),
    url(r'^app-2/', include(app_2, namespace='app-2')),
    url(r'^app-4/', include(app_4, namespace='app-4')),
    url(r'^app-3/', include(app_3, namespace='app-3')),
]

app_1/urls.py
from django.conf.urls import url
from .views import index, login_sso, update_status, add_status
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^auth-login/', auth_login, name='auth_login'),
	url(r'^auth-logout/', auth_logout, name='auth_logout'),
	url(r'^login-sso/', login_sso, name='login_sso'),
	url(r'^update-status/', update_status, name='update_status'),
	url(r'^add-status/', add_status, name='add_status'),
]

app_2/urls.py
from django.conf.urls import url
from .views import index, edit

urlpatterns = [
	url(r'^profile/', index, name='index'),
	url(r'^profile/edit', edit, name='edit'),
	# url()
]

app_3/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

app_4/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

app_1/models.py
from django.db import models

# Create your models here.
class Mahasiswa(models.Model):
	name = models.CharField(max_length=30)
	npm = models.CharField(max_length=10, primary_key=True, unique=True)
	angkatan = models.CharField(max_length=4)

class Status(models.Model):
	mahasiswa = models.ForeignKey(Mahasiswa)
	description = models.CharField(max_length=280)
	created_date = models.DateTimeField(auto_now_add=True)

app_2/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Keahlian(models.Model):
	npm = models.CharField(max_length=10)
	ahli = models.CharField(max_length=255)
	level = models.CharField(max_length=12)
	email = models.CharField(max_length=100)
	profil = models.CharField(max_length=50)

app_3/models.py
from django.db import models

# Create your models here.

app_4/models.py
from django.db import models

class Mahasiswa(models.Model):
	name = models.CharField(max_length=30)
	npm = models.CharField(max_length=10)
	angkatan = models.CharField(max_length=4)

class Keahlian(models.Model):
	keahlian = models.CharField(max_length=255)
	level = models.CharField(max_length=12)

app_1/forms.py
from django import forms

class Status_Form(forms.Form):
	status_attrs = {
		'class' : 'form-control',
	}

	description = forms.CharField(label='', required=True, max_length=280, widget=forms.TextInput(attrs=status_attrs))

app_1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import Status_Form
# Create your views here.
response = {}

def index(request):
	if 'user_login' in request.session:
		return HttpResponseRedirect(reverse('app-2:profile'))
	else:
		html = 'app_1/landing-page.html'
		return render(request, html, response)

def login_sso(request):
	if 'user_login' in request.session:
		return HttpResponseRedirect(reverse('app-2:profile'))
	else:
		html = 'app_1/login.html'
		return render(request, html, response)

def update_status(request):
	if 'user_login' in request.session:
		html = 'app_1/update_status.html'
		return render(request, html, response)
	else:
		html = 'app_1/landing-page.html'
		return render(request, html, response)

def add_status(request):
	form = Status_Form(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['description'] = request.POST['description']
		npm = get_data_user(request, 'kode_identitas')
		mahasiswa = Mahasiswa.objects.get(npm=npm)
		status = Status(mahasiswa=mahasiswa, description=response['description'])
		status.save()
		all_status = Status.objects.all()
		response['all_status'] = all_status
		html = 'app_1/update-status.html'
		return HttpResponseRedirect(reverse('app-1:update_status'))
	else:
		return HttpResponseRedirect(reverse('app-1:update_status'))

def get_data_user(request, tipe):
    data = None
    if tipe == "user_login" and 'user_login' in request.session:
        data = request.session['user_login']
    elif tipe == "kode_identitas" and 'kode_identitas' in request.session:
        data = request.session['kode_identitas']

    return data

app_2/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponseRedirect
from django.shortcuts import render
from app_1.models import Mahasiswa, Status
from .models import Keahlian
from django.urls import reverse
from app_1.models import Mahasiswa

# Create your views here.
response = {}

def index(request):
	html = 'app_2/app_2.html'
	response['nama'] = request.session['user_login']
	response['npm'] = request.session['kode_identitas']
	response['jumlah_status'] = Status.objects.all().count()
	response['status_baru'] = Status.objects[0]
	response['email'] = Keahlian.objects.filter(npm=npm).email
	response['keahlian'] = Keahlian.objects.filter(npm=npm).ahli
	response['profil'] = Keahlian.objects.filter(npm = npm).profil
	return render(request, html, response)

def edit(request):
	html = 'app_2/edit.html'

	return render(request, html, response)

app_3/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponseRedirect
#from app_2.models import 
import requests
# Create your views here.
response = {}
MATKULS = 'https://private-e52a5-ppw2017.apiary-mock.com/riwayat'

def index(request):
    html = 'app_3/dashboard.html'
    response['riwayat'] = get_data()
    return render(request, html, response)

def get_data():
    data = requests.get(MATKULS)
    return data.json()

app_4/views.py
from django.shortcuts import render
#from .models import Mahasiswa, Keahlian
from app_1.models import Mahasiswa
from app_2.models import Keahlian

def index(request):
    mahasiswa_list = Mahasiswa.objects.all()

    #Mahasiswa.objects.create(name="Eddie Wayne", npm="1306937591", angkatan="2013")
    #Mahasiswa.objects.create(name="Ford Allen", npm="0906120472", angkatan="2009")
    #Mahasiswa.objects.create(name="Mary Laird", npm="1006338013", angkatan="2010")
    #Mahasiswa.objects.create(name="Charles Alan", npm="0806733874", angkatan="2008")
    #Mahasiswa.objects.create(name="Frank Finn", npm="1206397735", angkatan="2012")
    #Mahasiswa.objects.create(name="Terry Mack", npm="1106844517", angkatan="2011")
    #Mahasiswa.objects.create(name="Ann Claire", npm="0706883958", angkatan="2007")
    #Mahasiswa.objects.create(name="Jimmie Dale", npm="0906822739", angkatan="2009")
    #Mahasiswa.objects.create(name="Emma Dale", npm="1306733210", angkatan="2013")
    #Mahasiswa.objects.create(name="David Ryan", npm="1106299411", angkatan="2011")
    #Mahasiswa.objects.create(name="Tressa Gail", npm="0806235512", angkatan="2008")
    #Mahasiswa.objects.create(name="Charlie Clyde", npm="1006235513", angkatan="2010")
    #Mahasiswa.objects.create(name="Zack Alan", npm="1006234414", angkatan="2010")
    #Mahasiswa.objects.create(name="Sarah Michelle", npm="0906348815", angkatan="2009")
    #Mahasiswa.objects.create(name="Carol Kaye", npm="1106937716", angkatan="2011")
    #Mahasiswa.objects.create(name="Don Allan", npm="0806499517", angkatan="2008")
    #Mahasiswa.objects.create(name="John Preston", npm="1106093318", angkatan="2011")
    #Mahasiswa.objects.create(name="Betty Grace", npm="0906722619", angkatan="2009")
    #Mahasiswa.objects.create(name="Jack Carl", npm="1206899520", angkatan="2012")

    html = 'app_4/cari_mahasiswa.html'
    response = {}
    response['mahasiswa_list'] = mahasiswa_list
    return render(request, html, response)

app_1/templates/app_1/landing-page.html
{% extends "app_1/layout/base.html" %}

{% block content %}
<div >
	<a href="{% url 'app-1:login_sso' %}" class="btn btn-primary">
		Login Mahasiswa 
	</a>
</div>
{% endblock %}

app_1/templates/app_1/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="description" content="Login-Status">
   <meta name="author" content="{{author}}">
   <!-- bootstrap csss -->
   <link href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton:400,700">
   <title>
       {% block title %} Login & Status{% endblock %}
   </title>
</head>
<body>
   <header>
      
   </header>
   <content>
           {% block content %}
               <!-- content goes here -->
           {% endblock %}
   </content>
   <footer>
       <!-- TODO Block Footer dan include footer.html -->
       {% block footer %}
       
       {% endblock %}
   </footer>
   <!-- Jquery n Bootstrap Script -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   
   <!-- Custom Sweet Alert -->
   <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
   {% block javascript %}
   {% endblock %}
</body>
</html>

app_1/templates/app_1/login.html
{% extends "app_1/layout/base.html" %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <hr>
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'app-1:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}

app_1/templates/app_1/update_status.html
{% extends "app_1/layout/base.html" %}

{% block content %}
<section name="input-status">
	<div class="container">
		<h1 id="title">
			<font face="Calibri">
				Update Status
			</font>
		</h1>
		<form id="form" method="POST" action="{% url 'app-1:add_status' %}">
			{% csrf_token %}
			{{ status_form }}
			<button id="button" type="submit" class="btn btn-primary">
				POST
			</button>
		</form>
	</div>
</section>
<section>
	<div class="container">
		{% if status %}
			{% for data in status %}
				<div class="status-list">
					<p>{{ data.description }}</p>
					<p>{{ data.created_date }}</p>
				</div>
			{% endfor %}
		{% endif %}
	</div>
</section>
{% endblock %}

app_2/templates/app_2/app_2.html
{% extends "app_2/layout/base.html" %}

<div class="clearfix"></div>
<div class="container">

    <h3>Profile</h3>
    <div class="row">
        <div class="col-sm-2">
            <div class="thumbnail">
                <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
            </div>
            <!-- /thumbnail -->
        </div>
        <div class="col-sm-3">
            <div class="col">
              <div class="col">
                <button>Lihat Forum</button>
              </div>
              <br>
              <br>
              <br>
              <br>
              <br>
              <div class="col">
                <a href="{% url 'app-2:edit' %}">Edit Profile</a>
              </div>
            </div>
        </div>
        <div class="col-sm-7">
          <br>
          <div class="col">{{ jumlah_status }}</div>
          <div class="col">Jumlah Status</div>
          <br>
          <br>
          <div class="col status_baru">{{ status_baru }}</div>
        </div>
    </div>
</div>

<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#profile">Profile</a></li>
  <li><a data-toggle="tab" href="{% url 'app-3:index' %}">Riwayat</a></li>
  <li><a data-toggle="tab" href="{% url 'app-1:update_status' %}">Status</a></li>
</ul>

<div class="tab-content">
  <div id="profile" class="tab-pane fade in active">
    <p>Nama             : {{ nama }}</p>
    <p>NPM              : {{ npm }}</p>
    <p id="keahlian">Keahlian         : <i>Kosong</i></p>
    <p id="email">Email            : <i>Kosong</i></p>
    <p id="linkedin">Profile Linkedin : <i>Kosong</i></p>
  </div>
  <!-- <div id="menu1" class="tab-pane fade">
    <h3>Menu 1</h3>
    <p>Some content in menu 1.</p>
  </div>
  <div id="menu2" class="tab-pane fade">
    <h3>Menu 2</h3>
    <p>Some content in menu 2.</p>
  </div> -->
</div>

<script type="text/javascript">
	
</script>

app_2/templates/app_2/edit.html
<div class="clearfix"></div>
<div class="container">

    <h3>Profile</h3>
    <div class="row">
        <div class="col-sm-2">
            <div class="thumbnail">
                <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
            </div>
            <!-- /thumbnail -->
        </div>
        <div class="col-sm-3">
            <div class="col">
              <div class="col">
                <button>Simpan</button>
              </div>
              <br>
              <br>
              <br>
              <br>
              <br>
              <div class="col">
                <button href="app-2:simpan">Simpan/button>
              </div>
            </div>
        </div>
        <div class="col-sm-7">
          <br>
          <div class="col">{{ jumlah_status }}</div>
          <div class="col">Jumlah Status</div>
          <br>
          <br>
          <div class="col status_baru">{{ status_baru }}</div>
        </div>
    </div>
</div>

<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#profile">Profile</a></li>
  <li><a data-toggle="tab" href="#menu1">Riwayat</a></li>
  <li><a data-toggle="tab" href="#menu2">Status</a></li>
</ul>

<div class="tab-content">
  <div id="profile" class="tab-pane fade in active">
    <button></button>
  </div>
  <!-- <div id="menu1" class="tab-pane fade">
    <h3>Menu 1</h3>
    <p>Some content in menu 1.</p>
  </div>
  <div id="menu2" class="tab-pane fade">
    <h3>Menu 2</h3>
    <p>Some content in menu 2.</p>
  </div> -->
</div>

<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key: '815s0g0e8s5tsk'
    authorize: true
    onLoad: onLinkedInLoad
    scope: r_basicprofile r_emailaddress
</script>
<script type="text/javascript">
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }
    
    // Use the API call wrapper to request the member's profile data
    function getProfileData() {
        IN.API.Profile("me").fields("id", "first-name", "last-name", "headline", "location", "picture-url", "public-profile-url", "email-address").result(displayProfileData).error(onError);
    }

    // Handle the successful return from the API call
    function displayProfileData(data){
        var user = data.values[0];
        document.getElementById("picture").innerHTML = '<img src="'+user.pictureUrl+'" />';
        document.getElementById("name").innerHTML = user.firstName+' '+user.lastName;
        document.getElementById("intro").innerHTML = user.headline;
        document.getElementById("email").innerHTML = user.emailAddress;
        document.getElementById("location").innerHTML = user.location.name;
        document.getElementById("link").innerHTML = '<a href="'+user.publicProfileUrl+'" target="_blank">Visit profile</a>';
        document.getElementById('profileData').style.display = 'block';
    }

    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }
    
    // Destroy the session of linkedin
    function logout(){
        IN.User.logout(removeProfileData);
    }
    
    // Remove profile data from page
    function removeProfileData(){
        document.getElementById('profileData').remove();
    }
</script>

app_2/templates/app_2/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="app_2">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/lab_6.css' %}" /> -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.4.1.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/qunit/qunit-2.4.1.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <title>
        {% block title %} Profile {% endblock %}
    </title>
</head>
<body>
<header>
    {% include "app_2/partials/header.html" %}
</header>
<content>
    <div id="qunit" hidden></div>

    <!-- Themes -->
    <div class="container">
    <select style="width: 200px;" class="my-select"></select>
    <br/><button class="btn apply-button">Change Theme</button>

    {% block content %}
    {% endblock %}

</content>
<footer>
    <!-- TODO Block Footer dan include footer.html -->
    {% block footer %}
    {% include "app_2/partials/footer.html" %}
    {% endblock %}
</footer>
<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
<!-- <script src="{% static 'js/lab_6.js' %}"></script> -->
</body>

app_2/templates/app_2/partials/footer.html
<div class="container"><p>>Dibuat dengan cinta setulus hati oleh Arkha Sayoga Mayadi, Fari Qodri Andana, Hema Mitta Kalyani, Rico Putra Pradana</p></div>

app_2/templates/app_2/partials/header.html
<nav class="navbar navbar-inverse bg-primary fixed-top navbar-light bg-faded">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Selamat Datang, {{ nama }}</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/update-status/">
        <img src="http://cliparting.com/wp-content/uploads/2016/10/Person-people-icon-clipart-kid.png" style="width:25px;height:25px">
        {{ nama }}
        </a></li>
        <a href="{% url 'app-1:auth_logout' %}" type="button" class="btn btn-danger">Sign Out</a>
      </ul>
      
    </div><!--/.nav-collapse -->
  </div>
</nav>

app_2/templates/app_2/update_status.html
{% extends "app_1/layout/base.html" %}

{% block content %}
<section name="input-status">
	<div class="container">
		<h1 id="title">
			<font face="Calibri">
				Update Status
			</font>
		</h1>
		<form id="form" method="POST" action="{% url 'app-2:add_status' %}">
			{% csrf_token %}
			{{ status_form }}
			<button id="button" type="submit" class="btn btn-primary">
				POST
			</button>
		</form>
	</div>
</section>
<section>
	<div class="container">
		{% if status %}
			{% for data in all-status %}
				<div class="status-list">
					
				</div>
			{% endfor %}
		{% endif %}
	</div>
</section>
{% endblock %}

app_3/templates/app_3/app_3.html
{% extends "app_3/layout/base.html" %}

{% block content %}
<section class="main-riwayat" id="riwayat">
    <div class="container">
        <div class="row">
            <div class = "col">
                <div class = "scroll">
                    <table class = "table table-hover table-condensed" style="width: 100%;">
                        <tr>
                            <th>Nama Matkul</th>
                            <th>Nilai</th>
                        </tr>
                        <div>
                            {% for data in riwayat %}
                                <tr>
                                    <td style="text-align: center;"> {{ data.kelas.nm_mk_cl.nm_mk }}</td>
                                    <td class = "nilai" style="text-align: center;"> {{ data.nilai }}</td>
                                </tr>
                            {% endfor %}
                        </div>
                    </table>
                </div>
            </div>
            <!-- <div class = "col">
                <button id = "hide"> Hide Score </button>
            </div> -->
        </div>
    </div>
</section>
{% endblock %}

app_3/templates/app_3/dashboard.html
{% extends "app_3/layout/base.html" %}

{% block content %}
<section class="main-riwayat">
        <div>
                
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs nav-justified" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#status" aria-controls="home" role="tab" data-toggle="tab"> Status </a>
                        </li>
                        <li role="presentation">
                            <a href="#profile" aria-controls="settings" role="tab" data-toggle="tab"> Profile </a>
                        </li>
                        <li role="presentation">
                            <a href="#riwayat" aria-controls="settings" role="tab" data-toggle="tab"> Riwayat </a>
                        </li>
                    </ul>
                
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="status">
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="profile">
                            <!-- Apply the same here -->
                            {% include 'app_2/app_2.html' %}
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="riwayat">
                            <!-- Apply the same here -->
                            {% include 'app_3/app_3.html' %}
                        </div>
                    </div>
                </div>
</section>
{% endblock %}

app_3/templates/app_3/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="description" content="Login-Status">
   <meta name="author" content="{{author}}">
   <!-- bootstrap csss -->
   <link href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton:400,700">
   <link rel="stylesheet" type="text/css" href="{% static 'css/app_3.css' %}" />
   <title>
       {% block title %} Profile {% endblock %}
   </title>
</head>
<body>
   <header>
      
   </header>
   <content>
           {% block content %}
               <!-- content goes here -->
           {% endblock %}
   </content>
   <footer>
       <!-- TODO Block Footer dan include footer.html -->
       {% block footer %}
       
       {% endblock %}
   </footer>
   <!-- Jquery n Bootstrap Script -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   
   <!-- Custom Sweet Alert -->
   <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
   <script src = "{% static 'js/app_3.js' %}"></script>
   {% block javascript %}
   {% endblock %}
</body>
</html>

app_4/templates/app_4/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="description" content="LAB 8">
   <meta name="author" content="{{author}}">
   <!-- bootstrap csss -->
   <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" type="text/css" href="{% static 'css/cari_mahasiswa.css' %}" />
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">

   <title>
       {% block title %} Cari Mahasiswa {% endblock %}
   </title>
</head>
<body style = "background-color: #dfe3ee">
   <div id="fb-root"></div>
   <script src="{% static 'js/cari_mahasiswa.js' %}"></script>
   <content>
           {% block content %}
               <!-- content goes here -->
           {% endblock %}
   </content>
   
   <!-- Jquery n Bootstrap Script -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   {% block javascript %}
   {% endblock %}
</body>
</html>